version: '3.8'
services: 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: client-download-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev